### ISSUE TITLE
run watch doesn't work

### ISSUE THREAD

**Issue by ghost** [codingphasedotcom/Starter-Kit-2018#3]
Hi Joe

I was stumbled on your (awesome) videos today and followed your instructions to use your starter kit. I had to install things twice to make it work, but all files eventually were in place like they were in the video. Though when I hit npm run watch, there was nothing followed. If I typed in browser localhost:3000 though, I can see the page. Do you have any ideas why I did wrong to resulting this?

Many thanks for the starter kit and the videos!

Have a nice day,
Wei

**Comment by HermonSolomon** [comment]
@VidiLux 
Hi Vidi, did you manage to get around it i'm experiencing the same out come, it seems to be watching the changes that i've made with sass but can't figure out why it doesn't launch the browser server window on npm run watch. Thanks in advance.

**Comment by ghost** [comment]
@HermonSolomon Hello Hermon, unfortunately I didn't sort that one out. I have been diving into other projects since, but I suspect this is caused by errors we have done during installing yarn or npm as later on when I was using Atom, I got this Lint incompatible errors which also linked to npm after googling. My npm knowledge is not enough to sort that out so I uninstalled everything. npm is on my to-learn list, so if I figured anything out in the future I will definitely share with you! In the meantime I was just wondering if @jaysg @codingphasedotcom could please give you a hand?
Sorry didn't really help you :(

**Comment by HermonSolomon** [comment]
Hi Wei,

@VidiLux Thanks for getting back to me, I hear you and that's fair play. I
myself even tried uninstalling npm but unfortunately i kept getting the
same errors. I just hope @jaysg @codingphasedotcom
<https://github.com/codingphasedotcom> makes his way to our rescue.

Thanks once again Wei :)

**Comment by mohouyizme** [comment]
Have you rename **renamethisfile.txt** (file) to **.babelrc** ? (make sure to remove **.txt** extention!).

![download](https://user-images.githubusercontent.com/23297439/38154789-fb119484-346b-11e8-9be8-d58bd4ddf15b.png)
![2](https://user-images.githubusercontent.com/23297439/38154802-05f46db8-346c-11e8-8571-37e66ab31fbb.png)

**Comment by mohouyizme** [comment]
Hey! Can you make a screenshot (or copy/paste) of the error message in terminal in order to know the problem?

**Comment by codingphasedotcom** [comment]
@VidiLux 
Sorry just saw this thread..

did you try installing node once again?
also are you on windows or mac or linux?
please share the errors that you are getting from terminal and google chrome console log

**Comment by HermonSolomon** [comment]
Hiya Mo! In regards to renaming the .babelrc as it already existed within
the root of the project folder upon download from Github, so didn't think
it would be necessary to have it rename the "changeMe.txt" file.

Here are the screenshots from my terminal. Like i mentioned earlier "npm
run watch" seems to be running it just doesn't spit out the local server:
3000 automatically.

Thanks for the shout back mate!.

**Comment by codingphasedotcom** [comment]
wait are you talking about the window opening automatically?

if thats the issue go to the gulp file look at the comments all you have to do is turn it on.

**Comment by codingphasedotcom** [comment]
on the gulpfile.js

```
browserSync.init({
        server: './public',
        notify: false,
        open: false //change this to true if you want the browser to open automatically 
    });
```

the reason i made it to false is because everytime you run npm run watch it creates a new tab instead of using the same one that it had open previous. After a while that will get you annoyed

**Comment by HermonSolomon** [comment]
Joe you the real MVP!

Thanks dude! 👊🏽
