### ISSUE TITLE
Craigslist Clone Deployment

### ISSUE THREAD

**Issue by Joseppi83** [codingphasedotcom/Starter-Kit-2018#8]
Anyone deployed the Craigslist Clone project to a shared hosting account?  If successful, what were your steps to configure it to deployment with shared hosting?

**Comment by codingphasedotcom** [comment]
You need a private server digital ocean, aws, heroku

**Comment by Joseppi83** [comment]
Yeah, thanks!  Found a YouTube video that answered my question last week, but forgot to close this issue.  https://www.youtube.com/watch?v=0WDuOIEnKN0&t=602s&index=153&list=WL

**Comment by Joseppi83** [comment]
Yeah, thanks!  Found a YouTube video last week that answered my question, but I forgot to close the issue.  https://youtu.be/0WDuOIEnKN0
